Aggregation functions now implemented as filters
dyn-tracing/tracing_sim pull request #49
Opened 2021-04-06 20:36 UTC by jessberg

This changes the aggregation function implementation - instead of being implemented as customized structs and imported directly, they now reuse the plugin_wrapper functionality, and compute the aggregation as a filter on storage.  One consequence of this is querying storage can no longer be constant.  By running the RPC that gets the query information through the filter and maintaining the same interface to the filter, we must make it mutable.  This means the return of the as_any_mut sim_element function.

Also, I deleted the custom version of petgraph.  We have our own isomorphism now, so we should just use regular petgraph wherever we can.

2021-04-06 21:00 UTC, fruffy commented
Quick comment based on the description alone, will look into this in-depth tomorrow. 
I do not think this is a good idea or should be merged. Mutating state on a query, which should be just a view, seems like a big anti-pattern. The function should never change lose the const qualifier. The likely reason that this seems necessary is a missing contract (a function that should be const or a get) or copy somewhere. If this can not be fixed that indicates a pretty big design flaw. 

For example, I thought aggregation was meant to be computed when something is sent to storage and not on query? If the filter demands the query to be mutable that indicates that it mutates state for each query. That seems wrong. It should only do that for incoming POSTs from the nodes. If the query is harmless, than it can also be computed without state, and that is a different kind of operator.

2021-04-07 08:12 UTC, fruffy commented
1) So the filter also acts on user queries. Ideally it should not do that, since those are basically out-of-band. They are not part of the application.  I guess this comes down to design. I see two options:
a) Storage is a standard database that stores the precomputed results and can be queried by users at whim. So once users have deployed their query, they can access storage data as they see fit. 
b) Storage is a pub/sub type of application that pushes results to a user as soon as there are any. The user has no control on how to transform the data unless they update the entire query. What pushing to a user means is at this point ill-defined. 

I do not know which one is the better path or what we want to solve with this tbh.

2021-04-07 08:13 UTC, fruffy requested changes

2021-04-07 08:13 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
1) It looks like you are retrieving results from the filter!? That is only volatile data. It should only be used for computation when writing or rather _committing_ a result that comes from a proxy filter. `get_avg` should probably be in `on_incoming_requests` and that is the result that is stored. Then none of this is necessary, too.

2021-04-07 13:15 UTC, jessberg commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Yes.  The reason we're storing data, and seemingly doing aggregation as well as collecting all the data, is this filter should work regardless of whether we have an aggregation function or not.  So in the case that we are not, I thought we had to collect the data because the "database" underneath us was dumb enough that it wasn't doing that.  I guess it comes down to making the filter completely useless if there is no aggregation function.  Will the storage server still be storing those results in that case?  And returning all the data when we query?

2021-04-07 15:21 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
The database should store whatever the filter transforms when a node has issued the HTTP dispatch. The filter may keep some volatile state for this, but the database ultimately saves the snapshot. Not sure what you mean with collecting data, our queries still only have on result per trace right? The storage server right now returns the list of all the keys and values that we have stored. Typically that should be a list of trace/result matches.

2021-04-07 15:22 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
We are using the ingress filter attached to storage to perform custom aggregation and computation. The database could also do that, but we have decided to use the filter instead. This does not extend to the reads (user queries though).

2021-04-07 15:26 UTC, jessberg commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
I thought the database does not store one result per trace.  The point of an aggregation function is that you're performing some function on all the data, and only storing the result of that function.  I guess the question is:   when you query storage while you have an aggregation function, does the filter intercept it and replace the "normal" record with its own aggregation function result?  Do we have two different queries for the general data stored vs filter-supplied aggregation function results?

2021-04-07 15:54 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
` I guess the question is: when you query storage while you have an aggregation function, does the filter intercept it and replace the "normal" record with its own aggregation function result`
No it should not. Unless the user asks for that by hooking up a listener that polls data like that. Which goes back to the explicit design choices I mentioned earlier. We should be clear about that.  What you see is what you get, there should not be any hidden side-effects. 

You also should be able to query a million times at any point in time without altering anything. This is violated when you require something unstable and ephemeral as a filter to maintain all the data. They are not designed for that, we are barely able to store state on them. The filter is really a hack that we exploit it for some specific purpose in-band. It only exists as part of the application deployment and not as part of the surrounding tools. It should not intercept any queries made by admins or developers that are debugging their deployment.

We can also store the final result in storage for now, which you can access without any side effects. I do not see any reason why this should not be possible for now. 
Personally, I believe there are two clean designs but both of them require work. 
If you remember Noria, you could try the "we store parts of the query" in our database system approach. This is essentially what we have right now. On a write, the database updates its result incrementally. This is the same as our filter intercepting the PUT request from the nodes and aggregating (not the user query, that is a read). The user then gets the current version of this "view" by querying.

The alternative is the classical DB approach, we actually deploy a real database that stores the per-trace results. Users then have the flexibility to use any type of query over those trace results, of which we have precomputed a large chunk for them. This is much easier to do and more general, but not in the style this project meant to go as far as I understand. Also it would require a change of the semantics.

2021-04-07 16:07 UTC, jessberg commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
First, it sounds like you are leaning towards the Noria approach.  As an aside, I'm not sure I see the parallels between our stuff and Noria except that we are precomputing queries as they come in, as Noria does.  Is there any other reason you find this an apt comparison?

Second, I just want to make sure I understand what you're describing. The filter would still hold the intermediate data for the aggregation, right?  And every time we write to the database with (trace_id:  value), we'd also write with the updated (aggregation_func_id: value), and then on querying, a user would just need to query the database with no interference from the filter?  I think this would make sense, and it would mean no changes to the underlying storage whether we have an aggregation function or not, which is nice.

2021-04-07 16:24 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
I was just using Noria as a reference because it was the most recent database paper we discussed. But I think some of the differential dataflow work can also be reapplied in our environment, part of the reason why I got interested there. I believe as soon as we start looking into multi-user approaches, we will likely end up with a similar system, because we essentially are working with a continuos dataflow and a fixed query.  

In a sense, what Noria does is to cache every query asked in their database and then maintain state for it. What we do is to store a single query (for now), but each node in our system is an operator, which maintains some specific state for it. This also includes the storage filter. Now we also incrementally update our results in a similar fashion. For every trace we have a write. Our storage filter is an aggregation function that updates its internal state and generates an incremental update, which is sent to storage. The users will see a snapshot of this at storage. Conceptually speaking, "writes", which are just new request traces coming in, propagate through our query graph in a similar way. 

Regarding your second paragraph, yeah basically. I was just thinking of the old design that used traces in storage. That is why I mentioned them. If we store the final result that is also fine, but we need to be careful with identifier conflicts for the result key (productpage-v1 is fairly generic).

2021-04-07 16:34 UTC, jessberg commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Okay cool.  I see the Noria connection now.

Yeah I think we want to be able to store an entire trace in storage - I've got the issue for that in the compiler but have not yet implemented it.  That way we will be able to be straddle the line between tracing and metrics, and I think make the system more general.  So instead of storing traces in storage, we just store some generic "value" that could be a trace or could just be an aspect of a trace.

Why are identifier conflicts for the result key an issue?  I thought we were storing (trace_id: result), and then the results will be "unique" because they are attached to unique trace IDs.

2021-04-07 16:41 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
So that was the current implementation of storing we had. Either incremental updates or all traces. If you take `count` these are two outcomes for example, it might look like this for three requests.
Identifier is node that stores:
Data in storage: `productpage-v1:1 -> productpage-v1:2 -> productpage-v1:3`
Identifier is trace:
Data in storage: `trace-id1:1 -> trace-id1:1,trace-id2:2 -> trace-id1:1,trace-id2:2,trace-id3:3`

2021-04-07 16:48 UTC, jessberg commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Okay I think the second approach makes more sense for now.  Then in addition to having 
trace-id1:1 -> trace-id1:1,trace-id2:2 -> trace-id1:1,trace-id2:2,trace-id3:3
we would also have
count: 1 -> count : 2 -> count : 3

Does that make sense?

2021-04-07 17:00 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Yeah that is okay as long as it does not require too much work to maintain both. Where is count computed?

2021-04-07 17:02 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Also how do you decide the label?

2021-04-07 17:03 UTC, jessberg commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Count would have some sort of intermediate state in the filter, eg, the last count.  For average, that intermediate state would be total and sum, and then every time you get a request, you send (avg: sum/total) to storage.  For a histogram, you keep a count of each bucket in the filter, and then when you send to storage, you edit the values and serialize it to a string.  So the intermediate computation, or the last computation that is necessary to get the next one, is stored in the filter, so it has that information to make the next value.

Alternatively we could have the filter query storage but I think that would get really messy really fast.

2021-04-07 17:05 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        x.data = self.avg.get_avg();
Okay sounds good.

2021-04-08 14:38 UTC, fruffy requested changes

2021-04-08 14:38 UTC, fruffy commented on libs/aggregation_example/src/avg.rs
> +        rpc_str.push_str(&self.avg.get_avg());
I would just merge get_avg into execute. It is the same process as far as I understand.

2021-04-08 14:38 UTC, fruffy commented on libs/sim/storage.rs
> +                print!("rpc data is {:?}", rpc.data);
This should be a log message or removed.

2021-04-08 14:48 UTC, fruffy approved these changes

2021-04-08 14:56 UTC, merged

2021-04-08 17:36 UTC, fruffy reviewed
example_envs/bookinfo/.gateway.rs.swp
Forgot to mention that this file should be deleted. Can you do that in the next pull request?