Channel changed to have capacity
dyn-tracing/tracing_sim pull request #8
Opened 2021-01-16 00:16 UTC by jessberg

I made channels have capacity as well.  This should lay the groundwork for having both edge and node objects that build off of channels, and then you can optionally set both the nodes' and edges' delays and capacities.  This should make the simulator more general.

2021-01-18 10:01 UTC, fruffy commented
I do not know much about the simulator but the way I understood it was that channels are just layers to links. Channels model additional properties such as delay or queues. Why is capacity needed? Or what role does it serve? Is it bandwidth or maximum queue size? @anirudhSK ?

2021-01-18 13:46 UTC, anirudhSK commented
We need to model a limited capacity in RPCs per second for the total egress rate from a node. Because of the limited capacity, there will eventually be queue buildup as well. This is a reasonable model for how network capacity in the public cloud works: https://cloud.google.com/compute/docs/network-bandwidth

2021-01-19 16:10 UTC, jessberg commented
> I made channels have capacity as well. This should lay the groundwork for having both edge and node objects that build off of channels, and then you can optionally set both the nodes' and edges' delays and capacities. This should make the simulator more general.

Per the meeting, this has now changed to just give an egress rate to the links.  So the main files changed are sim/src/link.rs and sim/src/main.rs in order to give it an egress rate.  All the other files are changes to Cargo.toml and adding the petgraph modified library so that automated tests run well;  if petgraph is in a separate repo, then the tests can't access it and they fail, so I'm just combining repos.

2021-01-21 16:35 UTC, fruffy requested changes

2021-01-21 16:35 UTC, fruffy commented on libs/filter_lib/Cargo.toml
> +petgraph = { path = "../petgraph" }
I would recommend adding petgraph as a git submodule and track changes there. Makes maintenance a lot easier.

2021-01-21 17:43 UTC, fruffy approved these changes

2021-01-21 17:46 UTC, merged